language: java

install:
  - pushd $HOME
  - pwd
  - wget http://download.pivotal.com.s3.amazonaws.com/gemfire/9.3.0/pivotal-gemfire-9.3.0.zip
  - unzip pivotal-gemfire-9.3.0.zip
  - gfsh version
  - popd

jdk:
  - oraclejdk8

env:
   global:
      - GEMFIRE=$HOME/pivotal-gemfire-9.3.0
      - PATH=$GEMFIRE/bin:$PATH

script:
  - gfsh version
  - scripts/generateCerts.sh ldap
  - scripts/generateCerts.sh gemfire
  - ./gradlew clean build
